spring.application.name=catalogocanzoni

# Configurazione del database MySQL
spring.datasource.url=jdbc:mysql://localhost:3306/canzoni_db
spring.datasource.username=root
spring.datasource.password=root


spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.forward-headers-strategy=framework